### ISSUE TITLE
how to stop location subscription i have multiple screens and subscription run multiple times

### ISSUE THREAD

**Issue by jabbarmemon** [MustansirZia/react-native-fused-location#15]

**Comment by MustansirZia** [comment]
Hi @jabbarmemon! Did you use `FusedLocation.off(this.subscription);` in your `componentWillUnmount`? Just call this to remove subscriptions wherever you have kept them.
Otherway of doing it would be to just call `FusedLocation.stopLocationUpdates ()` once from somewhere in your app and no further location updates would be emitted anywhere. 

It would be really helpful if you can post some code.

**Comment by MustansirZia** [comment]
I will have to close this issue due to inactivty.

**Comment by jabbarmemon** [comment]
i have to use background geolocation so i can not stop it componentWillUnmount
