### ISSUE TITLE
how to check if subscription is already running ?

### ISSUE THREAD

**Issue by jabbarmemon** [MustansirZia/react-native-fused-location#16]

**Comment by MustansirZia** [comment]
Hi @jabbarmemon!
Right now, the library doesn't have such an API but it uses `DeviceEventEmitter` underneath which may have something you could use.

```js
import { DeviceEventEmitter } from 'react-native';

// Somewhere in your code.
// To get all the registered subscriptions (callbacks), you can call.
const listeners  = DeviceEventEmitter.listeners('fusedLocation');

// To see if the subscription is running, simply find your callback inside the listeners array like so.
const running = listeners.indexOf(callbackYouWishToFind) !== -1;
```

Documentation for `DeviceEventEmitter` doesn't exist officially but you can find it inside the react-native code base right [here](https://github.com/facebook/react-native/blob/master/Libraries/vendor/emitter/EventEmitter.js).

Tell me if this works out! :)

**Comment by jabbarmemon** [comment]
thanks dear

const listeners = DeviceEventEmitter.listeners('fusedLocation');
if (listeners[0] != undefined) {

} else {

this._checkETrack();

}

**Comment by MustansirZia** [comment]
Close the issue if you're satisfied.
