### ISSUE TITLE
getting nothing

### ISSUE THREAD

**Issue by dekemega** [MustansirZia/react-native-fused-location#25]
Hi,
i am using [react-native-android-location-enabler](https://github.com/Richou/react-native-android-location-enabler) to enable the gps so we can get the user location .. 
here is what i did

`    async getLocation() {
        RNAndroidLocationEnabler.promptForEnableLocationIfNeeded({interval: 10000, fastInterval: 5000})
            .then(async (data) => {
                console.log(data);
                try {
                    const granted = await PermissionsAndroid.request(
                        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, {
                            title: 'App needs to access your location',
                            message: 'App needs access to your location ' +
                            'so we can let our app be even more awesome.'
                        }
                    );
                    if (granted == PermissionsAndroid.RESULTS.GRANTED) {
                        FusedLocation.setLocationPriority(FusedLocation.Constants.HIGH_ACCURACY);
                        const location = await FusedLocation.getFusedLocation();
                        console.log(location);
                    } else {
                        console.log('Not granted');
                    }
                } catch (err) {
                    console.log('err',err);
                }
            }).catch(err => {
            console.log(err);
        });
    }
`
if the gps is off before this code it will ask to turn it on then the fusedLocation doesn't return anything at all ( not error even ) ... if the the gps is previously turned on the fusedLocation works just fine .

		"react-native": "0.54.2",
		"react-native-android-location-enabler": "^1.0.5",
		"react-native-fused-location": "^0.2.1",
		"react-native-maps": "https://github.com/react-community/react-native-maps.git",

i think this might help [locationclient-getlastlocation-return-null](https://stackoverflow.com/questions/16830047/locationclient-getlastlocation-return-null)

**Comment by MustansirZia** [comment]
Hello @dekemega!
I understand your situation and in this case, surely the last location that is returned must be null as pointed out in the attached question. But this library makes a point to request a NEW location update if that's the case inside the `getFusedLocation` method [here](https://github.com/MustansirZia/react-native-fused-location/blob/e5d5e4ce9129c95912249bd72471d6644d9a384e/android/src/main/java/com/mustansirzia/fused/FusedLocationModule.java#L122-L141).
In your case try lowering down the accuracy a bit and then trying again via the `setLocationPriority` method. 
Also, how long did you wait for the location? Sometimes, a new location update takes a few seconds more.

**Comment by MustansirZia** [comment]
I would also suggest making sure that you have the latest version of the library installed by following these steps.
• `react-native unlink react-native-fused-location`.
• `npm install react-native-fused-location --save`.
• `react-native link react-native-fused-location`.
•  Reinstall the app on your phone.

**Comment by dekemega** [comment]
Thank you very much

**Comment by MustansirZia** [comment]
Welcome!
