### ISSUE TITLE
can't find variable PermissionAndroid.

### ISSUE THREAD

**Issue by jinaddavid** [MustansirZia/react-native-fused-location#30]
Hi there!
I am using react-native-fused-location in my Project i followed the example [](https://github.com/MustansirZia/react-native-fused-location)  , But when i run the project its not working , the error i got is 

can't find variable PermissionAndroid.

**Comment by MustansirZia** [comment]
I believe you've just started to dive into react-native. Just add this line to your imports and you're good to go.
`import { PermissionsAndroid } from 'react-native';`

I had left out this import intentionally as this was obvious. :)
