### ISSUE TITLE
Execution failed for task ':react-native-fused-location:verifyReleaseResources'.

### ISSUE THREAD

**Issue by rendomnet** [MustansirZia/react-native-fused-location#35]
when i'm doing "./gradlew assembleRelease"

this error occurs:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fused-location:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by faizalshap** [comment]
Had the same issue, turns out it is because of the compileSdkVersion. 
Editing build.gradle file of this package by going to node_modules and changing compileSdkVersion to the one used in app.gradle worked for me.
