### ISSUE TITLE
Need to lock down the com.google.android.gms:play-services-location version to avoid build breakage

### ISSUE THREAD

**Issue by hoboman313** [MustansirZia/react-native-fused-location#43]
This lib currently breaks RN builds due to the latest release of play-services-location: https://developers.google.com/android/guides/releases#june_17_2019

This dep should be locked down to 16:+

**Comment by MustansirZia** [comment]
@hoboman313 That is correct. I'm going to do that in just a few. Just merged #42. Will also push an update soon.

**Comment by MustansirZia** [comment]
Alright. Play services dep is now locked to `16.+`. Also in the meanwhile updated the default version for compile sdk and build tools version. Also updated the android gradle version. Here's [all about it](https://github.com/MustansirZia/react-native-fused-location/commit/357a20b79b96f4da4b0658005d2d0797955677dc).

Do let me know how it goes. The new version for the package is [`0.5.0`](https://www.npmjs.com/package/react-native-fused-location).
