### ISSUE TITLE
PermissionsAndroid

### ISSUE THREAD

**Issue by sihitejulio** [MustansirZia/react-native-fused-location#5]
why can't find variable PermissionsAndroid in didmount?

**Comment by MustansirZia** [comment]
Really sorry for the confusion. PermissionsAndroid is actually a react native module that is imported like this. It comes with react native. 
`import {PermissionsAndroid} from 'react-native'`
It's in the docs. https://facebook.github.io/react-native/docs/permissionsandroid.html
