### ISSUE TITLE
RN 0.47.x - removal of createJSModules

### ISSUE THREAD

**Issue by Metroninja** [MustansirZia/react-native-fused-location#7]
FusedLocationPackage.java needs the following lines removed to work with RN >0.47

```
  @Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }
```

**Comment by MustansirZia** [comment]
@Metroninja Fixed! 
https://github.com/MustansirZia/react-native-fused-location/commit/e997380c715834d110195d37257596d7b23a1264
