### ISSUE TITLE
It Doesn't provide Network Provider Info ???

### ISSUE THREAD

**Issue by anujsinghwd** [MustansirZia/react-native-fused-location#8]
>I am using this code for android  
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import FusedLocation from 'react-native-fused-location';

export default class netLoc extends Component {

  constructor(props){
      super(props);
      this.state= {
        loc: []
      }
  }

  async componentDidMount() {
    // const granted = await PermissionsAndroid.request(
    //                PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, {
    //                    title: 'App needs to access your location',
    //                    message: 'App needs access to your location ' +
    //                    'so we can let our app be even more awesome.'
    //                    }
    //                );
    if (true) {
    
       FusedLocation.setLocationPriority(FusedLocation.Constants.HIGH_ACCURACY);
       
       // Get location once. 
       const location = await FusedLocation.getFusedLocation(); 
       this.setState({lat: location.latitude, long: location.longitude}); 
       
       // Set options.
       FusedLocation.setLocationPriority(FusedLocation.Constants.BALANCED); 
       FusedLocation.setLocationInterval(20000);
       FusedLocation.setFastestLocationInterval(15000); 
       FusedLocation.setSmallestDisplacement(10);
       
       
       // Keep getting updated location
       FusedLocation.startLocationUpdates();
       
       // Place listeners.
       this.subscription = FusedLocation.on('fusedLocation', location => {
          const locs = JSON.stringify(location);
          //console.log(location); 
          this.setState({loc: locs});

       }); 
    } 
  }

                  
  render() {
    return (
      <View>
       <Text> { this.state.loc }  </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('netLoc', () => netLoc);`

**Comment by MustansirZia** [comment]
Hi @anujsinghwd! I think what you mean is the location provider, the name of the technology that powers the current location request. I'm aware that it can be a cell tower request or a WIFI assisted request or a GPS request. But you should also be aware that Google now takes care of all these by itself and gives us what is called as the Fused API. It's basically a fusion of all the above methods and it decides by itself which method would be optimal. This library is built on the fused api and thus the provider inside the location object would always be `fused.` The underlying provider is automatically masked by google. 
You can use the `setLocationPriority` function to cater to your needs and make the request biased to a specific underlying location provider.
Read more about it [here](https://stackoverflow.com/questions/6775257/android-location-providers-gps-or-network-provider).

**Comment by MustansirZia** [comment]
Closed due to inactivity.

**Comment by anujsinghwd** [comment]
thanku @MustansirZia but it is still not working

**Comment by MustansirZia** [comment]
@anujsinghwd What exactly do you need?
